### ISSUE TITLE
Possible incompatibility with ShadowJar

### ISSUE THREAD

**Issue by hypherionmc** [Matyrobbrt/RegistrationUtils#1]
Hey. Firstly, AWESOME library. Definitely made my life a lot easier.

The plugin seems to have an incompatibility with ShadowJar. It was working perfectly until I set up a shadowJar task to shade another library, then it stopped including your library. It would only include the shaded library.

Is there any specific configuration to get this work? This was on the Forge side of multiloader btw

**Comment by Matyrobbrt** [comment]
Yes, in your Forge `build.gradle` add `reg.configureJarTask(shadowJar)`.
Example: https://github.com/AOCAWOL/BYG/blob/1.18.X/Forge/build.gradle#L131

**Comment by hypherionmc** [comment]
Ffs I saw that and completely forgot about it..... Thank you so much

**Comment by Matyrobbrt** [comment]
It's fine, it wasn't obvious in the README. I'll update it to include that information.

**Comment by Matyrobbrt** [comment]
There https://github.com/Matyrobbrt/RegistrationUtils#jar-inclusion

**Comment by hypherionmc** [comment]
Hmmm, I'm getting this after adding that line:
```
A problem occurred evaluating project ':Forge'.
> Could not find method configureJarTask() for arguments [task ':Forge:reobfShadowJar'] on extension 'reg' of type com.matyrobbrt.registrationutils.gradle.RegExtension.
```

**Comment by Matyrobbrt** [comment]
What version of the plugin are you using?

**Comment by hypherionmc** [comment]
0.2.6

**Comment by Matyrobbrt** [comment]
Can you show me your build.gradle

**Comment by hypherionmc** [comment]
Here you go, this is the forge one: https://paste.firstdarkdev.xyz/yowuhalono.gradle

**Comment by Matyrobbrt** [comment]
`reg.configureJarTask(reobfShadowJar)` this is wrong, use `reg.configureJarTask(shadowJar)`, it will be obfuscated as the jar will have the library shaded before being reobf

**Comment by hypherionmc** [comment]
Let me try. Give me a couple of minutes

**Comment by Matyrobbrt** [comment]
Also, unrelated but I use [this](https://github.com/Matyrobbrt/RegistrationUtils/blob/master/build.gradle#L128-L133) method to remove the dependencies from the pom

**Comment by hypherionmc** [comment]
Will take a look at that. Thanks :)

So now my forge jar is completely empty, only containing a META-INF directory. I don't know what I did wrong: https://paste.firstdarkdev.xyz/idalodilib.gradle

**Comment by Matyrobbrt** [comment]
I don't see anything visibly wrong there. Is your mod open source / does it have a GitHub? I'll try to see if I can fix it locally.

**Comment by Matyrobbrt** [comment]
Never mind, found the issue, and I can reproduce it on a normal workspace that isn't multiloader nor has reg:
```groovy
reobf {
    shadowJar {
        dependencies {
            include('me.hypherionmc.night-config:toml:3.6.5_custom')
            include('me.hypherionmc.night-config:core:3.6.5_custom')

            relocate 'me.hypherionmc.nightconfig', 'shadow.hypherionmc.nightconfig'
        }
        classifier ''
    }
}
```
This is _very_ wrong. The shadowJar task should be configured outside that block:
```groovy
shadowJar {
       dependencies {
            include('me.hypherionmc.night-config:toml:3.6.5_custom')
            include('me.hypherionmc.night-config:core:3.6.5_custom')

            relocate 'me.hypherionmc.nightconfig', 'shadow.hypherionmc.nightconfig'
        }
        classifier ''
}
reobf {
    shadowJar {}
}
```
@hypherionmc

**Comment by hypherionmc** [comment]
Hmmm, I've always used shadowjar like that, but lemme try

**Comment by hypherionmc** [comment]
Same result. Removing the shadowJar config completely works fine again.... Urgh

**Comment by hypherionmc** [comment]
Nevermind, got it to finally work....

Forgot to include `dependency(` in the shadowjar `include` lines. Sorry for wasting your time

**Comment by Matyrobbrt** [comment]
Glad I could help :)

**Comment by hypherionmc** [comment]
Also seems like doing `gradlew clean build` breaks some things as well.

```Execution failed for task ':Common:compileJava'.
> Could not resolve all files for configuration ':Common:compileClasspath'.
   > Could not find me.hypherionmc.craterlib.systems.reg:regutils:0.2.6.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/me/hypherionmc/craterlib/systems/reg/regutils/0.2.6/regutils-0.2.6.pom
       - https://repo.spongepowered.org/repository/maven-public/me/hypherionmc/craterlib/systems/reg/regutils/0.2.6/regutils-0.2.6.pom
       - https://maven.firstdarkdev.xyz/releases/me/hypherionmc/craterlib/systems/reg/regutils/0.2.6/regutils-0.2.6.pom
       - file:/E:/mymcmods/craterlib/build/registrationutils/cache/me/hypherionmc/craterlib/systems/reg/regutils/0.2.6/regutils-0.2.6.pom
       - file:/E:/mymcmods/craterlib/build/registrationutils/cache/me/hypherionmc/craterlib/systems/reg/regutils/0.2.6/regutils-0.2.6.jar
       - https://libraries.minecraft.net/me/hypherionmc/craterlib/systems/reg/regutils/0.2.6/regutils-0.2.6.pom
       - https://maven.minecraftforge.net/me/hypherionmc/craterlib/systems/reg/regutils/0.2.6/regutils-0.2.6.pom
     Required by:
         project :Common
         ```

**Comment by Matyrobbrt** [comment]
That's not a surprise, `clean` generally breaks FG as well, there's no sane solution to that. It's recommended you don't use `clean` in mod environments

**Comment by hypherionmc** [comment]
Hehe. I use it on Jenkins, so will just add my usual workaround
