### ISSUE TITLE
MC 1.20.1 Gradle 8.7 incompatible with registrationutils

### ISSUE THREAD

**Issue by hexnowloading** [Matyrobbrt/RegistrationUtils#13]
A problem occurred configuring root project 'Dungeon Now Loading Multiloader Mod'.
> Could not create an instance of type com.matyrobbrt.registrationutils.gradle.RegExtension.
   > Could not find 'versionParser'

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by LogicTechCorp** [comment]
I am also getting this issue with Gradle 8.8. I am using RU version 1.20.1 on MC 1.19.4.

**Comment by LogicTechCorp** [comment]
@hexnowloading have you found a fix or workaround?

**Comment by Matyrobbrt** [comment]
Should be fixed in `1.20.1-2.0.1`

**Comment by Witixin1512** [comment]
I'm getting the following error during `regutilsIdeSync` after updating to RegUtils `1.20.1-2.0.1` using both Gradle 8.7 and 8.8:

```
Circular dependency between the following tasks:
:forge:addMixinsToCommonRegCombinedJar
\--- :forge:compileJava
     \--- :forge:commonRegCombinedJar
          \--- :forge:addMixinsToCommonRegCombinedJar (*)
```

**Comment by LogicTechCorp** [comment]
> I'm getting the following error during `regutilsIdeSync` after updating to RegUtils `1.20.1-2.0.1` using both Gradle 8.7 and 8.8:
> 
> ```
> Circular dependency between the following tasks:
> :forge:addMixinsToCommonRegCombinedJar
> \--- :forge:compileJava
>      \--- :forge:commonRegCombinedJar
>           \--- :forge:addMixinsToCommonRegCombinedJar (*)
> ```

Same here.
