### ISSUE TITLE
Group change has issues

### ISSUE THREAD

**Issue by lilypuree** [Matyrobbrt/RegistrationUtils#3]
https://github.com/lilypuree/Decorative-Blocks/blob/1.19/build.gradle

I've updated the group field of the RegistrationUtils configuration to use 'lilypuree.decorative_blocks.registration', however the library files are relocated to 'lilypuree, stohun.decorative_blocks.registration' because I used "${mod_author}.${mod_id}.registration" before. I've tried restarting the ide invalidating caches, using the clean task etc but there's no difference, the libraries are relocated to the wrong directory and I can't use it.

**Comment by lilypuree** [comment]
![image](https://user-images.githubusercontent.com/38712797/185197470-103f80f1-ef35-4037-9656-44baa3f31af8.png)

**Comment by Matyrobbrt** [comment]
Have you tried deleting the `build` folder (of all subprojects _and_ in the root project)?

**Comment by lilypuree** [comment]
removing regutils from modules and libraries in the project setting, removing all build folders and reloading actually changed the directory.

**Comment by Matyrobbrt** [comment]
Fixed in `1.19-1.3.0`: https://github.com/Matyrobbrt/RegistrationUtils/commit/b07fe2cfbfc551dc0f0ce8c58b93e63a2c89f981
