### ISSUE TITLE
[1.20.2} MissingValueException on setup

### ISSUE THREAD

**Issue by GirafiStudios** [Matyrobbrt/RegistrationUtils#6]
First of all, thanks for making this! Will save me a lot of headache with MultiLoader projects for sure.

I´ve been trying to implement it for 1.20.2, but I´m getting the following error when trying to add it to my build.gradle
![image](https://github.com/Matyrobbrt/RegistrationUtils/assets/6305377/10e73d8e-29fe-449c-bfda-be7ab5b2487e)
I could just be stupid & missing something obvious, but I have no clue that the issue could be, based on the error I´m getting.

My build.gradle:
https://gist.github.com/GirafiStudios/b687b6996af221b198f7128dd7f6fb5d

**Comment by Matyrobbrt** [comment]
The subproject name and the name in the `projects` block must match exactly.
